version: "2.0"
services:
  frontend_develop:
      build: .
      image: "babequeue_frontend:develop"
      ports: 
        - "8000:80"
      restart: always
      volumes:
        - "/etc/home/applications/babequeue/build /www/html/branches/develop"
     
      container_name: "babequeue_frontend_develop"
 
networks:
  default:
    external:
      name: nginx-proxy



